services:
  whisper:
    image: jmgirard/wsl-whisper
    ports:
      - "${RS_PORT}:8787"
    environment:
      - PASSWORD=${RS_PASS}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
